//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Pages
{
    public partial class Checkout
    {
        protected global::System.Web.UI.WebControls.Panel pnlSinCarrito;

        protected global::System.Web.UI.WebControls.Panel pnlCheckout;

        protected global::System.Web.UI.WebControls.Repeater rptItems;

        protected global::System.Web.UI.WebControls.TextBox txtDireccionEnvio;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDireccionEnvio;

        protected global::System.Web.UI.WebControls.Label lblTotal;

        protected global::System.Web.UI.WebControls.Button btnFinalizarCompra;

        protected global::System.Web.UI.WebControls.Label lblMensaje;
    }
}
