//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Pages
{
    public partial class Compras
    {
        protected global::System.Web.UI.WebControls.Label LblTotal;

        protected global::System.Web.UI.WebControls.Panel PanelSinResultados;

        protected global::System.Web.UI.WebControls.Repeater RptCompras;

        protected global::System.Web.UI.WebControls.Repeater RptComprasMobile;
    }
}
