//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Pages
{
    public partial class MisCompras
    {
        protected global::System.Web.UI.WebControls.Label LblTotal;

        protected global::System.Web.UI.WebControls.Panel PanelSinResultados;

        protected global::System.Web.UI.WebControls.Repeater RptMisCompras;

        protected global::System.Web.UI.WebControls.Repeater RptMisComprasMobile;
    }
}
