// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddBloqueoCuentaUsuario : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202606070000000_AddBloqueoCuentaUsuario"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return null; }
        }
    }
}
