//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI {


    public partial class Site_Mobile {

        /// <summary>
        /// HeadContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// PnlPublicLinks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlPublicLinks;

        /// <summary>
        /// PnlUserSession control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlUserSession;

        /// <summary>
        /// LblUsuarioLogueado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblUsuarioLogueado;

        /// <summary>
        /// BtnCerrarSesion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnCerrarSesion;

        /// <summary>
        /// PnlPublicLinksMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlPublicLinksMobile;

        /// <summary>
        /// PnlUserSessionMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlUserSessionMobile;

        /// <summary>
        /// LblUsuarioLogueadoMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblUsuarioLogueadoMobile;

        /// <summary>
        /// BtnCerrarSesionMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnCerrarSesionMobile;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
