//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{


    public partial class SiteMaster
    {

        /// <summary>
        /// Control HeadContent.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// Control PnlPublicLinks.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlPublicLinks;

        /// <summary>
        /// Control PnlUserSession.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlUserSession;

        /// <summary>
        /// Control LblUsuarioLogueado.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblUsuarioLogueado;

        /// <summary>
        /// Control BtnCerrarSesion.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnCerrarSesion;

        /// <summary>
        /// Control PnlPublicLinksMobile.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlPublicLinksMobile;

        /// <summary>
        /// Control PnlUserSessionMobile.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlUserSessionMobile;

        /// <summary>
        /// Control LblUsuarioLogueadoMobile.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblUsuarioLogueadoMobile;

        /// <summary>
        /// Control BtnCerrarSesionMobile.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnCerrarSesionMobile;

        /// <summary>
        /// Control MainContent.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
